name: Go workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          python-version: "1.14"
      - name: Install requirements
        run: go get -t -v ./...
      - name: Run tests and collect coverage
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
