name: Node workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Node Coverage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install requirements
        run: npm i
      - name: Run tests and collect coverage
        run: c8 ava
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
